server:
  port: 8080

spring:
  application:
    name: dessertBee
  jwt:
    secret:
      access: ${JWT_SECRET_ACCESS}
      refresh: ${JWT_SECRET_REFRESH}
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  devtools:
    restart:
      enabled: true   # 자동 재시작 활성화
    livereload:
      enabled: true   # 브라우저 자동 새로고침

  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 50MB

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-authentication-method: client_secret_post
            redirect-uri: ${KAKAO_REDIRECT_URI}
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GOOGLE_MAIL_USERNAME}
    password: ${GOOGLE_MAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org:
      hibernate:
        SQL: debug                  # Hibernate SQL 로깅
        orm:
          jdbc:
            bind: trace            # SQL 파라미터 로깅 (최신 Hibernate 버전)
    com:
      dessertbee: debug             # 프로젝트 패키지 로깅

springdoc:
  api-docs:
    path: /api-docs                 # 기본 OpenAPI 문서 경로 변경
  swagger-ui:
    path: /swagger-ui               # Swagger UI 경로 변경
    enabled: true                    # Swagger UI 활성화

aws:
  s3:
    bucket-name: desserbee-bucket
    region: ap-northeast-2
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}


