spring:
  application:
    name: dessertBee

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  devtools:
    restart:
      enabled: true   # 자동 재시작 활성화
    livereload:
      enabled: true   # 브라우저 자동 새로고침

  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

logging:
  level:
    org:
      hibernate:
        SQL: debug                  # Hibernate SQL 로깅
        orm:
          jdbc:
            bind: trace            # SQL 파라미터 로깅 (최신 Hibernate 버전)
    com:
      dessertbee: debug             # 프로젝트 패키지 로깅

springdoc:
  api-docs:
    path: /api-docs                 # 기본 OpenAPI 문서 경로 변경
  swagger-ui:
    path: /swagger-ui               # Swagger UI 경로 변경
    enabled: true                    # Swagger UI 활성화

s3:
  base-url: ${S3_BASE_URL}

