spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: ${KAKAO_REDIRECT_URI_PROD}
          apple:
            redirect-uri: ${APPLE_REDIRECT_URI_PROD}
#  elasticsearch:
#    uris: http://desserbee-es:9200
#  graphql:
#    cors:
#      allowed-origins: "https://desserbee.com,https://www.desserbee.com,http://desserbee.com,http://www.desserbee.com,https://api.desserbee.com,https://frontend-desserbee-web-git-vercel-test-eepyzs-projects.vercel.app/"
app:    # 추가
  client:    # 추가
    redirect-url: "https://desserbee.com"    # 추가

# 프로덕션 환경에서는 Swagger UI 비활
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false
