spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: "http://localhost:8000/kakao-oauth-test.html"
  graphql:
    cors:
      allowed-origins: "http://localhost:3000"
  data:
    redis:
      host: localhost
      port: ${SPRING_DATA_REDIS_PORT}
app:
  client:
    redirect-url: "http://localhost:3000"
