spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  # 개발 환경에서 devtools 활성화
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: "http://localhost:8000/kakao-oauth-test.html"
  graphql:
    cors:
      allowed-origins: "http://localhost:3000"
# 개발 환경에서는 상세 로깅 활성화
logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace
    com:
      dessertbee: debug