spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  # 개발 환경에서 devtools 활성화
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: "http://localhost:8000/kakao-oauth-test.html"
          apple: # ngrok 새로킬 때마다 변경되는 값임.
            redirect-uri: https://e05c-210-107-70-217.ngrok-free.app/ko/oauth/callback/apple
          apple-app:
            redirect-uri: https://e05c-210-107-70-217.ngrok-free.app/apple-oauth-test.html

  graphql:
    cors:
      allowed-origins: "http://localhost:3000"
  data:
    redis:
      host: localhost
      port: ${SPRING_DATA_REDIS_PORT}
#  elasticsearch:
#    uris: http://localhost:9200
app:
  client:
    redirect-url: "http://localhost:3000"

# 개발 환경에서는 상세 로깅 활성화
logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace
#      springframework:
#        data:
#          elasticsearch:
#            client: debug
#      co:
#        elastic:
#          clients: debug
    com:
      dessertbee: debug